version: "3.9"
services:
 nginx:
  image: nginx
  ports:
   - "80:80"
  volumes:
   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
   - ./source:/var/www/html
 php:
  image: php:8.1-fpm
  ports:
   - "9000:9000"
  volumes:
   - ./source:/var/www/html